version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: assignment_user
      POSTGRES_PASSWORD: assignment_pass
      POSTGRES_DB: assignment_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U assignment_user -d assignment_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
