import Header from '@/components/Header';
import StdNo from '@/components/Footer';
import Copyright from '@/components/Copyright';
import { ThemeProvider } from "@/components/theme-provider"
import type { Metadata } from "next";
import './globals.css'

export const metadata: Metadata = {
  title: {
    template: '%s | LTU Moodle App',
    default: 'LTU Moodle App',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <div>
          <main>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
              storage="cookie"
            >
              <Header />
              {children}
            </ThemeProvider>
          </main>
          <StdNo />
          <Copyright />
        </div>
      </body>
    </html>
  )
}
